name: Docker Image CI

on:
  push:
    branches:
      - '*'
    tags:
      - '*'


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and push Docker images
      uses: docker/build-push-action@v1.1.0
      with:
        repository: asakuram/mirai
        username: asakuram
        password: ${{ secrets.hubtoken }}
        tag_with_ref: true
        dockerfile: Dockerfile.hub

  
