FROM alpine

WORKDIR /app

RUN apk add --no-cache python3 openjdk8-jre

ADD . /app
RUN pip3 install -r requirements.txt && \
    python3 bootstrap.hub.py && \
    echo Pure > /app/content/.wrapper.txt

CMD python3 bootstrap.hub.py && \
    java -Dmirai.account=$MIRAI_ACCOUNT -Dmirai.password=$MIRAI_PASSWORD -jar mirai-console-wrapper-*.jar --update KEEP
